CREATE TABLE `dbc_accesstoken` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT UNSIGNED NOT NULL,
  `token` CHAR(60) NOT NULL,
  `label` VARCHAR(60) NULL DEFAULT NULL,
  `expires` TIMESTAMP NULL DEFAULT NULL,
  `scope` LONGTEXT NULL DEFAULT NULL,
  `disabled` BOOLEAN NOT NULL DEFAULT FALSE,
  `renewed` TIMESTAMP NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `user_id` (`user_id`)
) DEFAULT CHARSET=utf8mb4;

ALTER TABLE `dbc_row_action`
  ADD `api` BOOLEAN NOT NULL AFTER `data`;

ALTER TABLE `dbc_user`
  ADD `apiaccess` BOOLEAN NOT NULL AFTER `admin`
